run:
  timeout: 5m
  go: "1.23"
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - prealloc
    - gocritic
    - revive
    - gocyclo
    - dupl
    - goconst
    - mnd
    - lll
    - nakedret
    - noctx
    - paralleltest
    - testpackage
    - tparallel
    - wastedassign
    - whitespace
  disable:
    - typecheck

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gomnd:
    checks: argument,case,condition,operation,return,assign
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - gocyclo
        - dupl
    - path: examples/
      linters:
        - mnd
        - gocyclo
        - dupl
        - goconst
    # Exclude Go 1.23 standard library typecheck issues
    - linters:
        - typecheck
      source: "go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.11.linux-amd64/src/"
    - linters:
        - typecheck
      source: "go/pkg/mod/github.com/!burnt!sushi/toml@v1.5.0/"
    - linters:
        - typecheck
      source: "go/pkg/mod/github.com/go-logr/"
    - linters:
        - typecheck
      source: "go/pkg/mod/go.opentelemetry.io/otel@v1.36.0/" 