package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/kdsmith18542/gokit/i18n"
	"github.com/kdsmith18542/gokit/i18n/editor"
)

func main() {
	localesDir := "./locales"
	if _, err := os.Stat(localesDir); os.IsNotExist(err) {
		_ = os.Mkdir(localesDir, 0755)

		// Create comprehensive sample translation files
		_ = os.WriteFile(localesDir+"/en.toml", []byte(`# English locale file
# Generated by GoKit i18n Editor

welcome = "Welcome to our application!"
goodbye = "Goodbye, see you soon!"
hello = "Hello, {{.Name}}!"
item = "1 item"
items = "{{.Count}} items"
price = "Price: {{.Amount}}"
login = "Login"
logout = "Logout"
register = "Register"
email = "Email"
password = "Password"
submit = "Submit"
cancel = "Cancel"
save = "Save"
delete = "Delete"
edit = "Edit"
search = "Search"
filter = "Filter"
sort = "Sort"
loading = "Loading..."
error = "An error occurred"
success = "Operation completed successfully"
confirm = "Are you sure?"
yes = "Yes"
no = "No"
`), 0644)

		_ = os.WriteFile(localesDir+"/es.toml", []byte(`# Spanish locale file
# Generated by GoKit i18n Editor

welcome = "¡Bienvenido a nuestra aplicación!"
goodbye = "¡Adiós, hasta pronto!"
hello = "¡Hola, {{.Name}}!"
item = "1 elemento"
items = "{{.Count}} elementos"
price = "Precio: {{.Amount}}"
login = "Iniciar sesión"
logout = "Cerrar sesión"
register = "Registrarse"
email = "Correo electrónico"
password = "Contraseña"
submit = "Enviar"
cancel = "Cancelar"
save = "Guardar"
delete = "Eliminar"
edit = "Editar"
search = "Buscar"
filter = "Filtrar"
sort = "Ordenar"
loading = "Cargando..."
error = "Ocurrió un error"
success = "Operación completada exitosamente"
confirm = "¿Estás seguro?"
yes = "Sí"
no = "No"
`), 0644)

		_ = os.WriteFile(localesDir+"/fr.toml", []byte(`# French locale file
# Generated by GoKit i18n Editor

welcome = "Bienvenue dans notre application!"
goodbye = "Au revoir, à bientôt!"
hello = "Bonjour, {{.Name}}!"
item = "1 élément"
items = "{{.Count}} éléments"
price = "Prix: {{.Amount}}"
login = "Se connecter"
logout = "Se déconnecter"
register = "S'inscrire"
email = "E-mail"
password = "Mot de passe"
submit = "Soumettre"
cancel = "Annuler"
save = "Enregistrer"
delete = "Supprimer"
edit = "Modifier"
search = "Rechercher"
filter = "Filtrer"
sort = "Trier"
loading = "Chargement..."
error = "Une erreur s'est produite"
success = "Opération terminée avec succès"
confirm = "Êtes-vous sûr?"
yes = "Oui"
no = "Non"
`), 0644)

		_ = os.WriteFile(localesDir+"/de.toml", []byte(`# German locale file
# Generated by GoKit i18n Editor

welcome = "Willkommen in unserer Anwendung!"
goodbye = "Auf Wiedersehen, bis bald!"
hello = "Hallo, {{.Name}}!"
item = "1 Element"
items = "{{.Count}} Elemente"
price = "Preis: {{.Amount}}"
login = "Anmelden"
logout = "Abmelden"
register = "Registrieren"
email = "E-Mail"
password = "Passwort"
submit = "Absenden"
cancel = "Abbrechen"
save = "Speichern"
delete = "Löschen"
edit = "Bearbeiten"
search = "Suchen"
filter = "Filtern"
sort = "Sortieren"
loading = "Laden..."
error = "Ein Fehler ist aufgetreten"
success = "Vorgang erfolgreich abgeschlossen"
confirm = "Sind Sie sicher?"
yes = "Ja"
no = "Nein"
`), 0644)
	}

	manager := i18n.NewManager(localesDir)
	handler := editor.NewHandler(editor.Config{
		LocalesDir: localesDir,
		Manager:    manager,
	})

	http.Handle("/i18n/editor/", http.StripPrefix("/i18n/editor", handler))

	fmt.Println("GoKit i18n Editor running at http://localhost:8080/i18n/editor/")
	fmt.Println("Features:")
	fmt.Println("- Table-based translation editing")
	fmt.Println("- Live search and filtering")
	fmt.Println("- Missing translation highlighting")
	fmt.Println("- Real-time save functionality")
	fmt.Println("- Modern, responsive UI")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
